image: ros:noetic-ros-core
before_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update -y
   - apt-get install -y --no-install-recommends apt-utils
   - apt-get install -y --no-install-recommends dialog
   - apt-get install -y cmake
   - apt-get install -y libprotobuf-dev protobuf-compiler
   - apt-get update -y >/dev/null && apt-get install -y git >/dev/null
   - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git >/dev/null
   - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
   - apt-get install -qq libpcl-dev ros-pcl-msgs >/dev/null

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_linux:
   stage: build
   script:
      - cd ..
      - mkdir build
      - cd build
      - cmake ..
      - make

